=== Building a PetaLinux Image for the APU

include::link-attributes.adoc[]

Our Linux software stack is based on {yocto-org}[the Yocto project].

In order to build it, we use {kas-github}[`kas`], which fetches and
builds bitbake based project. If you already know about Yocto, you
don't have to use `kas`. Our layer, `meta-scobc`, can be used as a
regular yocto layer.

==== Setup the Build Environment

[source,  bash]
----
$ sudo apt update
$ sudo apt install binutils chrpath cpio diffstat file g++ gawk gcc \
                   git git-lfs lz4 make python3 rpcsvc-proto zstd
----

==== Clone the Repository

[source,  bash]
----
$ git clone https://github.com/spacecubics/meta-scobc
$ cd meta-scobc
----

NOTE: `meta-scobc` uses {git-lfs}[Git Large File Storage (Git
LFS)]. Make sure you install it.

==== Install and Enable the Required Python Packages

[source,  bash]
----
$ uv sync
$ source .venv/bin/activate
----

==== Build the Minimal Image

With `kas`, it's easier than bitbake to build the whole system. Just
let it do the work with the following command.

[source,  bash]
----
$ kas build kas/scobc-v1.yml
----

`build/tmp/deploy/images/scobc-v1/` will contain the generated image files.

[source,  bash]
----
$ ls -l build/tmp/deploy/images/scobc-v1/*wic
build/tmp/deploy/images/scobc-v1/sc-image-minimal-scobc-v1-yyyyMMddHHmmss.wic
build/tmp/deploy/images/scobc-v1/sc-image-minimal-scobc-v1.wic@
----

NOTE: `sc-image-minimal-scobc-v1.wic` is a symlink to the latest build.

==== Build with New XSA File

When you update Versal configuration or add FPGA logic, you must
update the XSA file with your own. `meta-scobc` has a XSA file at the
following path:

[source]
----
meta-scobc/meta-scobc-v1/recipes-bsp/hdf/files/sc_obc_v1_versal.xsa
----

You can also update `HDF_URI` variable to point to a new XSA file.
