== Building and Running Zephyr RTOS for SC-OBC Module V1

=== Building Zephyr RTOS for SC-OBC Module V1

To build Zephyr RTOS for SC-OBC Module V1 is the same as any other
board. All you have to do is to specify SC-OBC Module V1 (`scobc_v1`)
with the `-b` option to `west build`.

[source,  bash]
----
$ cd ~/myproject/zephyr
$ west build -b scobc_v1 samples/hello_world
----

NOTE: Unfortunately, however, as of this writing, SC-OBC Module V1
port is not merged to the upstream, yet. The PR for the OBC is ready
and waiting for merge.

https://github.com/zephyrproject-rtos/zephyr/pull/98143

Make sure you are using the branch.

=== Running Zephyr RTOS on SC-OBC Module V1

To run Zephyr RTOS, you can use `west flash`.

For this step, we assume assume that the boot MODE is set to JTAG,
which means that `SW1` is set to all `ON`. See SC-OBC Module V1
Product Manual for more details.

Currently, for any AMD Versal based board including SC-OBC Module V1, `west
flash` requires you to have a valid PDI.

[source,  bash]
----
$ source /path/to/xilinx/2025.1/Vivado/settings64.sh
$ west flash --pdi /path/to/your.pdi
----

The command first load the specified PDI file, then load Zephyr RTOS
ELF file, and run it.

IMPORTANT: `west flash` for Versal-based board uses `xsdb`, instead of
popular OpenOCD, for it's backend. This means that you must have
`xsdb` in one of your `PATH` environment variable directories.

=== Creating a PDI with Zephyr RTOS

You can create a PDI with Zephyr RTOS in it. The PDI, then, can be
load from any boot device Versal supports.

To create a PDI, you use `bootgen`.

`bootgen` requires a `.bif` file. A sample `.bif` file is:

[source]
----
new_bif:
{
    image
    {
        { type = bootimage, file = /path/to/your.pdi }
    }
    image
    {
        name = apu_ss, id = 0x1c000000
        { core = r5-lockstep, file = ~/myproject/zephyr/build/zephyr/zephyr.elf }
    }
}
----

Save it as, say, `mytest.bif`, then:

[source, bash]
----
$ source /path/to/xilinx/2025.1/Vivado/settings64.sh
$ bootgen -arch versal -image mytest.bif -w -o boot.bin
----

`bootgen` is provided by AMD (Vivado or Vitis). Make sure you have
installed it and `source` the setup script before use.

Generated `boot.bin` can be placed on a SD card or can be written to
one of the SPI NOR flash memories.

To load the PDI from SD card, you have to set the boot MODE [3:0] pins
to "SD0 v3.0" or "0011" by setting SW1 of V1 Carrier Board
SC-MPN-0062A to "OFF OFF ON ON".

To load the PDI from one of the SPI Flash memories , you have to set
the boot MODE [3:0] pins to "QSPI32" or "0010" by setting SW1 of V1
Carrier Board SC-MPN-0062A to "OFF OFF ON OFF".

See Versal documentations for more details.
